POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node 3",
    "description": "Este é o terceiro vídeo sobre node",
    "duration": "180"
}

###

GET http://localhost:3333/videos?search=node
###

GET http://localhost:3333/videos

###
GET http://localhost:3333/videos/b2ae0923-7ba2-4b41-b0fe-816081f29b7e

###

PUT http://localhost:3333/videos/0dec9e9f-bfb2-4420-ba1f-63672e265589
Content-Type: application/json

{
    "title": "Video node",
    "description": "Este é o segundo vídeo sobre node",
    "duration": "180"
}

###

DELETE  http://localhost:3333/videos/0dec9e9f-bfb2-4420-ba1f-63672e265589