POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Este é o primeiro vídeo sobre node",
    "duration": "180"
}

###

GET http://localhost:3333/videos?search=Video
###

GET http://localhost:3333/videos

###
GET http://localhost:3333/videos/cfc5e3df-bbe1-49fd-9c5d-a29c173f361e

###

PUT http://localhost:3333/videos/cfc5e3df-bbe1-49fd-9c5d-a29c173f361e
Content-Type: application/json

{
    "title": "Video node",
    "description": "Este é o primeiro vídeo sobre node",
    "duration": "200"
}

###

DELETE  http://localhost:3333/videos/ffffsss